@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

POST {{baseUrl}}/accounts
Content-type: application/json

# @name create_account
{
  "name": "Marcus Davanco",
  "email": "marcus@email9.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-type: application/json

{
  "email": "marcus@email9.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Chicken and eggs",
  "content": "Which came first, chicken or eggs?"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=2
Content-type: application/json
Authorization: Bearer {{authToken}}

